version: '3.9'
networks:
  siscon-docker.network:
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: siscon-docker.app
    restart: unless-stopped #O contêiner será reiniciados em caso de falha ou reinicialização da máquina host. (NO, ALWAYS)
    volumes: #faz um mapeamento do diretorio local para um diretorio dentro do container
      - .:/var/www/html
      - ./apache/vhost.conf:/etc/apache2/sites-enabled/000-default.conf
      - ./apache/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini 
      - ./storage/app:/var/www/html/storage/app
    ports:
      - "8787:80"
      - "4322:443"
    depends_on:
      - postgres_db
    networks:
      - siscon-docker.network
  postgres_db:
    image: postgres:15-alpine3.18
    container_name: siscon-docker.postgres
    restart: unless-stopped #O contêiner será reiniciados em caso de falha ou reinicialização da máquina host. (NO, ALWAYS)
    ports:
      - 5454:5432
    expose:
      - "5432"
    environment:
      POSTGRES_DB: siscon
      POSTGRES_USER: siscon
      POSTGRES_PASSWORD: siscon123456
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - siscon-docker.network
  redis:
    image: bitnami/redis:latest
    restart: always
    container_name: siscon-docker.redis
    tty: true
    volumes:
      - ./docker/redis:/bitnami/redis/data
    networks:
      - siscon-docker.network
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - REDIS_PASSWORD=root
    ports:
      - "6378:6379"
volumes:
  postgres_data:
